# Generated by Django 2.2.15 on 2020-08-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200821_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='first_field',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='user_name',
        ),
    ]
